[gcp_service_account]
type = "service_account"
project_id = "data-driven-attributes"
private_key_id = "957b43d1be08439f1b0a8616a27d7f467fac1fb2"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQD6K9LH8WMYAA+i
NTKUHeOMUZmFmIvXXWnT9QuC2fyi9mgmYhxvc1hwkaN7oo1AJYK3lpkg3V2fmp1t
NNcF60ZuQ32X6Sy2wBalZNxreKfJUl+XxN/wk59c5ldSS5kFuffU6J5dq6jZwT5H
MzBDL30YOZhYaeRIyAaf8CUcVJcEt4pDUEB7XDTh9tx53/Wwi+HDNBf6hUAsGHJu
1H0INGc0P0Iap6EJMxatz6FdRJrNkNp6u5NSxVmLlHiK7Tj1Z+4o7vwtb4FU7+Am
6OPxH4O/K4GXA6V95PAcelmpwp0MOzQ1tuOfVaNjihIxScsRzgEGsh8YpMTSnPKM
RhvaQOiZAgMBAAECggEAdcOcYQ+x8JHSyi5VpWDehWbCKJ/zMEnib+r55Lp90S7C
P1NPBG3dU3xTY3dVG72sp4SGh/B8yo2LjuVhVQF4cZ5mqFSU/mA1KN1uX074WO5k
XnrIWiT7z00FDRHWMlplHj30kq6keQEdMoIXtYDM19MA8pnCYzp5199BcPEm+AoK
EnSbNbF5dK5y+PLPHtZOnP9jZ6qYqHUomX/KZGPMXVTUMVUt9G7NbW0f4Bqhl/yq
4XD84dLCBtv9aK0Fv3h5UCOkutwwufNMx15H/v9rhAt7WyVAxbnSqmXkMH3mwe16
quQK2XBD6RB+mlhxj1rQ0U02p4yRSYkWki20vMAfAwKBgQD+HA9Iyp+uvPn/j3ZA
CQmogD0KwPQMyVhMHZv1EgpwEO00rccVuYcCPMDuc1kFfuKFMSjb5ngzTdlWqr05
iYKMmq89BC0ndyOpd7CgZw3JZa2K/wBYzfCkIR7wvAFtuXuhl9AGIeXig9tA080A
aI5fb4qZQVVurkYudhvWDUxRfwKBgQD8CENbI/IKj1H2cQFoAPmd7V/chNF+5/lC
wOSnrOPpLfUBftbiASdR6oQaD6jtX7kb++zF3QAoKDKDvfAOuBMhVOr8ruE1dRef
61nxVhHsPfnCT4hKGkbeJpgActN51UiT0jPwoCJPBGYGkdXlsZ0y7z4PjtllrvN9
sAWQCR4h5wKBgArvIik7rstSDl/UyH3Q5b1+ZyIDU30JXOdJjuBoulJAKDTQFXT1
2r1Z5+Nay0XVQ+H/T4bGz/1FKEj2Z9YF+LwcG9ZAS8Ea+0nbgJomVQ2JdoI4nscz
dVtaoX4yWM1j4dH+OlFJPB8XFWQguP1/gkDRB+G4UfjFPvfY1THMuK/5AoGAZKME
CkuTJYZPCyHaluX0xov3gD2EzbDhRjdx1kZiB0UzlPJJ6ZreUYZcU2+3W3mil7sD
s4pouqA6c4KPbcEw2llnL5jBErB7y36VvplItNWWenF5kWVmsOQmQ9+V9AsnXOdN
mCLJMFYoSy1GhN5kT+daF6pJwqGWVrTHs9kAMDcCgYEAngZyZ1EGk+bBoHhPk/w2
G6bcJ/Kz+mDZYWM1i9dPWaplVR3tvxvSYZvEVaOhmgvMQHmAGZAi54XM8J8LPlHq
r1PaXy1WXi+YXNStpCEjegAIERpr+Nnt+h/ThuWUEMrERsPuCMJP6GR+fSb7FiZw
Qm+WopeDAFbUlEtE/hZ5HMc=
-----END PRIVATE KEY-----"""
client_email = "538310479238-compute@developer.gserviceaccount.com"
client_id = "105396807136288688343"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/538310479238-compute%40developer.gserviceaccount.com"
universe_domain = "googleapis.com"
